services:
  mysql:
    image: mysql:8.0
    container_name: ventas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: ventas_db
      MYSQL_USER: ventas_user
      MYSQL_PASSWORD: ventas123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seged_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -padmin123"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7
    container_name: seged_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: seged
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - seged_net

  redis:
    image: redis:7-alpine
    container_name: seged_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - seged_net

  ventas-backend:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: ventas_backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ventas_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ventas_user
      SPRING_DATASOURCE_PASSWORD: ventas123
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - seged_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seged_backend
    restart: unless-stopped
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      APP_SESSION_TTL: PT30M
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: seged
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin123
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - seged_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seged_frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - seged_net
    command: npm run dev -- --host

volumes:
  mongo_data:
  mysql_data:
  redis_data:

networks:
  seged_net:
    driver: bridge
